"""WAF fingerprint detection via passive header analysis and active canary probes."""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from urllib.parse import urlparse

import requests

log = logging.getLogger(__name__)

CANARY_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1 --",
    "../../etc/passwd",
    "${7*7}",
    "{{7*7}}",
]

WAF_SIGNATURES: Dict[str, Dict[str, list]] = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "server": ["cloudflare"],
        "body_patterns": ["attention required! | cloudflare", "error 1010", "ray id"],
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-apigw-id", "x-amzn-waf"],
        "body_patterns": ["request blocked", "aws waf", "automated request"],
    },
    "modsecurity": {
        "headers": ["mod_security", "modsecurity"],
        "server": ["mod_security", "modsecurity"],
        "body_patterns": ["modsecurity", "not acceptable", "mod_security"],
    },
    "imperva": {
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "headers": ["x-iinfo", "x-cdn"],
        "body_patterns": ["incapsula", "imperva"],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn", "x-akamai-session-info"],
        "server": ["akamaighost", "akamai"],
        "body_patterns": ["access denied", "akamai"],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "server": ["sucuri"],
        "body_patterns": ["sucuri website firewall", "cloudproxy"],
    },
    "f5_bigip": {
        "headers": ["x-wa-info"],
        "cookies": ["ts", "bigipserver"],
        "server": ["bigip", "big-ip"],
    },
    "barracuda": {
        "cookies": ["barra_counter_session"],
        "headers": ["x-barracuda"],
        "body_patterns": ["barracuda", "barra_counter_session"],
    },
    "fortiweb": {
        "cookies": ["fortiwafsid"],
        "headers": ["fortiwafsid"],
        "body_patterns": ["fortigate", "fortiweb"],
    },
    "wordfence": {
        "body_patterns": ["wordfence", "generated by wordfence", "wfvt_"],
        "cookies": ["wfvt_"],
    },
}

BYPASS_LEVEL_MAP: Dict[str, str] = {
    "cloudflare": "aggressive",
    "aws_waf": "aggressive",
    "modsecurity": "aggressive",
    "imperva": "aggressive",
    "akamai": "aggressive",
    "sucuri": "light",
    "f5_bigip": "light",
    "barracuda": "light",
    "fortiweb": "light",
    "wordfence": "light",
    "generic": "light",
    "none": "none",
}


@dataclass
class WAFInfo:
    """Result of WAF detection for a target."""

    detected: bool
    vendor: str
    confidence: float
    evidence: List[str] = field(default_factory=list)
    block_status_code: Optional[int] = None
    bypass_level: str = "none"


class WAFDetector:
    """Identifies WAF presence via passive header inspection and active canary probes."""

    def __init__(self, timeout: int = 8):
        self._timeout = timeout

    def detect(self, target_url: str) -> WAFInfo:
        parsed = urlparse(target_url)
        base = f"{parsed.scheme}://{parsed.netloc}"

        evidence: List[str] = []
        vendor_scores: Dict[str, float] = {}

        # Phase 1: passive — benign GET to collect headers/cookies
        try:
            resp = requests.get(
                target_url, timeout=self._timeout, verify=False, allow_redirects=True
            )
        except requests.RequestException as exc:
            log.debug("WAF passive probe failed: %s", exc)
            return WAFInfo(detected=False, vendor="none", confidence=0.0)

        self._score_response(resp, vendor_scores, evidence, phase="passive")

        # Phase 2: active — send canary payloads that should trigger a WAF block
        block_status: Optional[int] = None
        for canary in CANARY_PAYLOADS:
            try:
                probe_url = f"{base}/?q={requests.utils.quote(canary)}"
                probe_resp = requests.get(
                    probe_url, timeout=self._timeout, verify=False, allow_redirects=True
                )
            except requests.RequestException:
                continue

            if probe_resp.status_code in (403, 406, 429, 503):
                block_status = probe_resp.status_code
                evidence.append(f"canary blocked with HTTP {probe_resp.status_code}")
                self._score_response(probe_resp, vendor_scores, evidence, phase="active")
                break

            self._score_response(probe_resp, vendor_scores, evidence, phase="active")

        if not vendor_scores:
            if block_status is not None:
                return WAFInfo(
                    detected=True,
                    vendor="generic",
                    confidence=0.4,
                    evidence=evidence,
                    block_status_code=block_status,
                    bypass_level=BYPASS_LEVEL_MAP["generic"],
                )
            return WAFInfo(detected=False, vendor="none", confidence=0.0)

        best_vendor = max(vendor_scores, key=vendor_scores.get)  # type: ignore[arg-type]
        raw_confidence = vendor_scores[best_vendor]
        confidence = min(raw_confidence, 1.0)

        return WAFInfo(
            detected=True,
            vendor=best_vendor,
            confidence=round(confidence, 2),
            evidence=evidence,
            block_status_code=block_status,
            bypass_level=BYPASS_LEVEL_MAP.get(best_vendor, "light"),
        )

    # ------------------------------------------------------------------

    def _score_response(
        self,
        resp: requests.Response,
        scores: Dict[str, float],
        evidence: List[str],
        phase: str,
    ) -> None:
        headers_lower = {k.lower(): v for k, v in resp.headers.items()}
        cookies = {c.name.lower(): c.value for c in resp.cookies}
        body_lower = (resp.text or "")[:8192].lower()
        server_header = headers_lower.get("server", "").lower()

        for vendor, sigs in WAF_SIGNATURES.items():
            for hdr in sigs.get("headers", []):
                if hdr.lower() in headers_lower:
                    scores[vendor] = scores.get(vendor, 0) + 0.3
                    evidence.append(f"[{phase}] header '{hdr}' → {vendor}")

            for srv_pat in sigs.get("server", []):
                if srv_pat.lower() in server_header:
                    scores[vendor] = scores.get(vendor, 0) + 0.4
                    evidence.append(f"[{phase}] server '{server_header}' matches {vendor}")

            for cookie_pat in sigs.get("cookies", []):
                for cname in cookies:
                    if cookie_pat.lower() in cname:
                        scores[vendor] = scores.get(vendor, 0) + 0.25
                        evidence.append(f"[{phase}] cookie '{cname}' → {vendor}")
                        break

            for body_pat in sigs.get("body_patterns", []):
                if re.search(re.escape(body_pat), body_lower):
                    scores[vendor] = scores.get(vendor, 0) + 0.35
                    evidence.append(f"[{phase}] body matched '{body_pat}' → {vendor}")
